default: &default
  encoding: utf-8
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  pool: <%= ENV.fetch('DB_POOL') { 5 } %>
  adapter: <%= ENV.fetch('DB_ADAPTER') { 'postgresql' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'teambuilder' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'teambuilder' } %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'teambuilder_dev' } %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'teambuilder_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'teambuilder_production' } %>
  variables:
    statement_timeout: 5000
